spring.application.name=api-gateway
server.port=8765
spring.config.import=optional:configserver:http://config-server:8888


eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=gateway,health,info,metrics
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always

