server.port=8081
spring.application.name=eureka-server

# Eureka Server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://eureka-server:8081/eureka

# Logging
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
logging.pattern.console=%C{1} [%-5level] %d{HH:mm:ss} - %msg%n

# Config Server connection
spring.cloud.config.uri=http://config-server:8888
spring.cloud.config.fail-fast=true

# Management endpoints
management.endpoints.web.exposure.include=health,info