eureka.client.service-url.defaultZone=http://eserver:8081/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=notification-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/kafka/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

resilience4j.circuitbreaker.instances.myService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.myService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.myService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.myService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.myService.waitDurationInOpenState=10000