eureka.client.service-url.defaultZone=http://eserver:8081/eureka

resilience4j.circuitbreaker.instances.kafkaService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.kafkaService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.kafkaService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.kafkaService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.kafkaService.automaticTransitionFromOpenToHalfOpenEnabled=true